---
- hosts: all
  tasks:

  - name: Copy yum repos
    copy:
     src: "{{ item }}"
     dest: "/etc/yum.repos.d/"
     backup: yes
    with_fileglob:
     - ../resources/yum.repos/*.repo

  - name: Install multiple packages
    yum:
     name: "{{ item.name }}"
    environment:
     disablerepo: '*'
     enablerepo: japco-centos,japco-epel
    with_items:
       # Database
     - { name: sqlite }
       # Devels
     - { name: python34 }
     - { name: python34-devel }
     - { name: python34-pip }

  - name: Install Python3 packages
    pip:
     name: flask
     executable: pip3.4

  - name: Copy configs
    copy:
     src: "../resources/{{ item.src }}"
     dest: "{{ item.dest }}"
     backup: yes
    register: config_change
    with_items:                                                 # numbers below are for readability
     - { src: "sshd_config", dest: "/etc/ssh/sshd_config" }                   #0
     - { src: "30-ca_psscm-nproc.conf", dest: "/etc/security/limits.d/" }     #1
     - { src: "31-ca_psscm-nofile.conf", dest: "/etc/security/limits.d/" }    #2

  - name: Reload sshd
    service:
     name: sshd
     enabled: yes
     state: reloaded
    when: config_change.results[0].changed

  - name: Create user ca_psscm
    user:
     name: ca_library
     home: /home/ca_library
     createhome: yes

  - name: Setting 777 on ephemeral
    file:
     path: /ephemeral
     state: directory
     mode: 0777

  - name: set timezone to Europe/Warsaw
    timezone:
     name: Europe/Warsaw
